[package]
name = "error-code"
version = "0.1.0"
edition = "2021"

[dependencies]
error-code-derive = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
http = { workspace = true }
thiserror ={ workspace = true }
